--- 
amazon: 
  access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  bucket: synthon-lodux
  region: us-east-2
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  service: S3
local: 
  access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  bucket: lodux-prueba
  region: us-east-2
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  service: S3
test: 
  root: <%= Rails.root.join("tmp/storage") %>
  service: Disk
